services:

  backend:
    build: ./backend
    container_name: red-tetris-backend
    restart: always
    networks:
      - public
      - proxy-net
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:8.0.15-noble
    container_name: red-tetris-mongodb
    restart: always
    networks:
      - public
      - proxy-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    command: mongod --quiet

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    container_name: red-tetris-frontend
    restart: always
    networks:
      - public
      - proxy-net
    environment:
      VITE_HOST_NAME: ${VITE_HOST_NAME}
      VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    ports:
      - "8080:80"

  bot-service:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: red-tetris-bot
    restart: always
    networks:
      - public
      - proxy-net
    depends_on:
      - backend

networks:
  public:
    driver: bridge
  proxy-net:
    external: true

volumes:
  mongo-data:
    driver: local
