services:

  backend:
    build: ./backend
    container_name: red-tetris-backend
    restart: always
    networks:
      - public
    environment:
      - DEBUG=backend:*
    ports:
      - "3000:3000"

  # frontend:
  #   build: ./frontend
  #   container_name: red-tetris-frontend
  #   restart: always
  #   networks:
  #     - public
  #   ports:
  #     - "8080:8080"

networks:
  public:
    driver: bridge
